### ISSUE TITLE
download button not working

### ISSUE THREAD

**Issue by NirVolo9** [Panopto-Video-DL/Panopto-Video-DL-browser#13] opened 2024-12-08 22:04 UTC
Hi,
Before the update, i could just download automatically the mp4 file via the button. 
Now it demands me to copy the link to your app, and it download gigas size FILE instead the mp4.
now it's way less comfortable using your tool....

**Comment by pizidavi** [comment] 2024-12-14 10:10
Hi, unfortunately, it is not something that can be solved

MP4 videos on Panopto are legacy, the more time passes, the more they disappear

Instead you can use [ffmpeg](https://www.ffmpeg.org/download.html) to download the video as MP4:
```shell
ffmpeg -f hls -i <uri> -c copy video.mp4
```

Instead of `<uri>` paste the link copied from Panopto-Video-DL-browser

**Comment by pizidavi** [comment] 2024-12-22 17:29
Duplicate of #12

**Closed as not planned by pizidavi** 2024-12-22 17:29 UTC
Labels: duplicate
