### ISSUE TITLE
Download produces non-functional file

### ISSUE THREAD

**Issue by kyky20024** [Panopto-Video-DL/Panopto-Video-DL-browser#14] opened 2024-12-20 21:51 UTC
This extension did not work when I tried to download a Panopto recording. The download button worked, but when I pasted each of the 3 source links, it did not properly download an mp4.
<img width="639" alt="Screenshot 2024-12-20 at 1 51 27 PM" src="https://github.com/user-attachments/assets/4f1060ca-f680-43a6-a599-05dd04eaf8aa" />

**Comment by pizidavi** [comment] 2024-12-22 17:29
Hi, unfortunately, it is not something that can be solved

MP4 videos on Panopto are legacy, the more time passes, the more they disappear

Instead you can use [ffmpeg](https://www.ffmpeg.org/download.html) to download the video as MP4:

```bash
ffmpeg -f hls -i <uri> -c copy video.mp4
```

Instead of `<uri>` paste the link copied from Panopto-Video-DL-browser

The link should be automatically copied if you are using the version [3.5.1](https://greasyfork.org/it/scripts/423661-panopto-video-dl)

**Comment by pizidavi** [comment] 2024-12-22 17:30
Duplicate of #12

**Closed as not planned by pizidavi** 2024-12-22 17:30 UTC
Labels: duplicate
